filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_docker_metadata: ~

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/datos/*.log
  

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

setup.kibana:
  host: "http://kibana:5601"

logging.level: debug
logging.selectors: ['*']